# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-29 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='myAuthor',
        ),
    ]
